language: python

python: "2.7"

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-nb

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip

env:
  global:
    - KEUY="VALUE"

# before_install:
#   - sudo apt-get update
#   - sudo apt-get --reinstall install -qq language-pack-en language-pack-nb
#   - cd vicdemo/
#   - ln -s ../vicvision/vic vic

install:
  - pip install -U pip wheel pytest
  - pip install -r requirements.txt
  # - pip install https://github.com/Vic-ai/python-hocr/archive/master.zip
  # - pip install https://github.com/loyning/python-24so/archive/master.zip

# before_script:
#   - pytest
#   - python manage.py migrate
#   - python manage.py createinitialrevisions

script: pytest --pep8 --flakes --doctest-modules --doctest-ignore-import-errors --doctest-continue-on-failure --html=report.html --self-contained-html --cov=vic --cov-report=html --verboseytest *

# before_script:
#   - cp docker-compose.travis.yml docker-compose.yml
#   - docker-compose -v
#   - docker-compose up -d
#   - sleep 10
#   - docker ps -a
#   - docker-compose exec -T web mix ecto.setup
#   - sleep 5
#   - docker-compose exec -T python3 manage.py migrate
#   - docker-compose exec -T python3 manage.py createinitialrevisions
#   - docker-compose exec -T python3 manage.py bower_install
#   - docker-compose exec -T python3 manage.py collectstatic --noinput

# script: docker-compose exec -T python3 manage.py test

# after_success:
#   - docker-compose stop